name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/MinimalWebApi
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 3.1
    - name: Build
      run: dotnet build src/MinimalWebApi.csproj --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
